### ISSUE TITLE
Cursor position is off on mac

### ISSUE THREAD

**Issue by clankill3r** [sampottinger/processing#103]
OSX 10.12.6

![2019-08-28 11 25 33](https://user-images.githubusercontent.com/738650/63843448-b15d6780-c986-11e9-9f3c-62b0f6f2c366.gif)

**Comment by hamoid** [comment]
Could it be related to high dpi / retina / font size / external monitor?

**Comment by sampottinger** [comment]
Ah good call @hamoid! It's the editor font size. Ooopphhh... it looks like its on the java11 branch. I'll look into that.

**Comment by sampottinger** [comment]
Ah gee... https://github.com/sampottinger/processing/blob/master/app/src/processing/app/syntax/JEditTextArea.java#L621

**Comment by sampottinger** [comment]
Hey there! I'll have to take a look at this again later. I think it has to do with deprecation in https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/text/Utilities.html but not totally sure. Unfortunately, I think JEdit has moved on from `JEditTextArea` so we are maybe in the business of updating it ourselves (http://syntax.jedit.org/ looks pretty dead). :-/

**Comment by hamoid** [comment]
I haven't tried this, but it seems under active development: 
http://bobbylight.github.io/RSyntaxTextArea/ 

It seems offer "copy styled" and mouse wheel scrolling (two things that were added to the text editor in the Processing IDE)

I'm curious about how good the autocomplete is. The current autocomplete doesn't work for me sometimes (maybe for objects? I can't remember).

**Comment by clankill3r** [comment]
> * Do you see the same behavior within mainline processing?

No

> * Do you see the same behavior with a jtextarea (see below)?

No

**Comment by sampottinger** [comment]
Thanks @clankill3r and @hamoid! (Sigh) It's not a great situation...

I'd prefer to switch out of JEdit Syntax for something like RSyntaxTextArea. For the record: I think the IDE is important for approachability and immediacy of Processing (I believe that the project would be worse off if we only supported `processing-java`) but I am also worried about JEdit Syntax and think RSyntaxTextArea seems like a good candidate for continuing that into the future. That said, the current code is not posing a clear stability / security issue and is still likely usable with modification. Given that JEdit Syntax has a possible sustainable path forward, I don't know if I (as a community contributor) quite get to make the call to transition libs. That said, I do see that @benfry and @fjenett looked into it at one point (https://github.com/processing/processing/issues/3199). While that work seems to have gone away, I would be willing to look into it again after talking with Ben... 

That in mind, I have found that Source Code Pro has had similar issues in other editors ([sublime](https://github.com/adobe-fonts/source-code-pro/issues/79) and [XCode](https://github.com/adobe-fonts/source-code-pro/issues/97)). Furthermore, using FontMetrics, I see that, in the problematic font sizes, the characters have widths with half pixels (*.5) which might be causing trouble with `Utilities.getTabbedTextWidth`. There isn't a clear contract that Java is violating (I don't think it's a JDK bug per-se) but it seems that there's a lot of code related to size of fonts that isn't graphics context aware ... which might be causing the issue.

Still looking! I'll report back soon.

**Comment by sampottinger** [comment]
Welp... Looks like I got a fix! :D Still want to chat with Ben about a possible move away from JEdit Syntax later but please see #107.

**Comment by sampottinger** [comment]
We're merged in! Thanks for your help!

**Comment by JackTheCat53** [comment]
Hello,
A completely new user downloading just to learn java, however, I am seeing this issue in the 4.0b1 windows release. I tried various fonts and text sizes with different but similar results. I'm going to use the latest release 3 instead for now.
